name: Node.js CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizado a la versión 3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Actualizado a la versión 3
        with:
          node-version: '16'  # Cambiado a una versión no obsoleta, puedes usar '20' si prefieres

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test